// ISO 3-letter country code → { flag emoji, display name }
const COUNTRY_MAP: Record<string, { flag: string; name: string }> = {
  AFG: { flag: '🇦🇫', name: 'Afghanistan' },
  ALB: { flag: '🇦🇱', name: 'Albania' },
  DZA: { flag: '🇩🇿', name: 'Algeria' },
  AND: { flag: '🇦🇩', name: 'Andorra' },
  AGO: { flag: '🇦🇴', name: 'Angola' },
  ARG: { flag: '🇦🇷', name: 'Argentina' },
  ARM: { flag: '🇦🇲', name: 'Armenia' },
  AUS: { flag: '🇦🇺', name: 'Australia' },
  AUT: { flag: '🇦🇹', name: 'Austria' },
  AZE: { flag: '🇦🇿', name: 'Azerbaijan' },
  BHS: { flag: '🇧🇸', name: 'Bahamas' },
  BHR: { flag: '🇧🇭', name: 'Bahrain' },
  BGD: { flag: '🇧🇩', name: 'Bangladesh' },
  BLR: { flag: '🇧🇾', name: 'Belarus' },
  BEL: { flag: '🇧🇪', name: 'Belgium' },
  BLZ: { flag: '🇧🇿', name: 'Belize' },
  BEN: { flag: '🇧🇯', name: 'Benin' },
  BTN: { flag: '🇧🇹', name: 'Bhutan' },
  BOL: { flag: '🇧🇴', name: 'Bolivia' },
  BIH: { flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
  BWA: { flag: '🇧🇼', name: 'Botswana' },
  BRA: { flag: '🇧🇷', name: 'Brazil' },
  BRN: { flag: '🇧🇳', name: 'Brunei' },
  BGR: { flag: '🇧🇬', name: 'Bulgaria' },
  BFA: { flag: '🇧🇫', name: 'Burkina Faso' },
  BDI: { flag: '🇧🇮', name: 'Burundi' },
  CPV: { flag: '🇨🇻', name: 'Cabo Verde' },
  KHM: { flag: '🇰🇭', name: 'Cambodia' },
  CMR: { flag: '🇨🇲', name: 'Cameroon' },
  CAN: { flag: '🇨🇦', name: 'Canada' },
  CAF: { flag: '🇨🇫', name: 'Central African Republic' },
  TCD: { flag: '🇹🇩', name: 'Chad' },
  CHL: { flag: '🇨🇱', name: 'Chile' },
  CHN: { flag: '🇨🇳', name: 'China' },
  COL: { flag: '🇨🇴', name: 'Colombia' },
  COM: { flag: '🇰🇲', name: 'Comoros' },
  COD: { flag: '🇨🇩', name: 'Congo (DRC)' },
  COG: { flag: '🇨🇬', name: 'Congo (Republic)' },
  CRI: { flag: '🇨🇷', name: 'Costa Rica' },
  HRV: { flag: '🇭🇷', name: 'Croatia' },
  CUB: { flag: '🇨🇺', name: 'Cuba' },
  CYP: { flag: '🇨🇾', name: 'Cyprus' },
  CZE: { flag: '🇨🇿', name: 'Czech Republic' },
  DNK: { flag: '🇩🇰', name: 'Denmark' },
  DJI: { flag: '🇩🇯', name: 'Djibouti' },
  DOM: { flag: '🇩🇴', name: 'Dominican Republic' },
  ECU: { flag: '🇪🇨', name: 'Ecuador' },
  EGY: { flag: '🇪🇬', name: 'Egypt' },
  SLV: { flag: '🇸🇻', name: 'El Salvador' },
  GNQ: { flag: '🇬🇶', name: 'Equatorial Guinea' },
  ERI: { flag: '🇪🇷', name: 'Eritrea' },
  EST: { flag: '🇪🇪', name: 'Estonia' },
  ETH: { flag: '🇪🇹', name: 'Ethiopia' },
  FJI: { flag: '🇫🇯', name: 'Fiji' },
  FIN: { flag: '🇫🇮', name: 'Finland' },
  FRA: { flag: '🇫🇷', name: 'France' },
  GAB: { flag: '🇬🇦', name: 'Gabon' },
  GMB: { flag: '🇬🇲', name: 'Gambia' },
  GEO: { flag: '🇬🇪', name: 'Georgia' },
  DEU: { flag: '🇩🇪', name: 'Germany' },
  GHA: { flag: '🇬🇭', name: 'Ghana' },
  GRC: { flag: '🇬🇷', name: 'Greece' },
  GTM: { flag: '🇬🇹', name: 'Guatemala' },
  GIN: { flag: '🇬🇳', name: 'Guinea' },
  GNB: { flag: '🇬🇼', name: 'Guinea-Bissau' },
  GUY: { flag: '🇬🇾', name: 'Guyana' },
  HTI: { flag: '🇭🇹', name: 'Haiti' },
  HND: { flag: '🇭🇳', name: 'Honduras' },
  HUN: { flag: '🇭🇺', name: 'Hungary' },
  ISL: { flag: '🇮🇸', name: 'Iceland' },
  IND: { flag: '🇮🇳', name: 'India' },
  IDN: { flag: '🇮🇩', name: 'Indonesia' },
  IRN: { flag: '🇮🇷', name: 'Iran' },
  IRQ: { flag: '🇮🇶', name: 'Iraq' },
  IRL: { flag: '🇮🇪', name: 'Ireland' },
  ISR: { flag: '🇮🇱', name: 'Israel' },
  ITA: { flag: '🇮🇹', name: 'Italy' },
  JAM: { flag: '🇯🇲', name: 'Jamaica' },
  JPN: { flag: '🇯🇵', name: 'Japan' },
  JOR: { flag: '🇯🇴', name: 'Jordan' },
  KAZ: { flag: '🇰🇿', name: 'Kazakhstan' },
  KEN: { flag: '🇰🇪', name: 'Kenya' },
  KWT: { flag: '🇰🇼', name: 'Kuwait' },
  KGZ: { flag: '🇰🇬', name: 'Kyrgyzstan' },
  LAO: { flag: '🇱🇦', name: 'Laos' },
  LVA: { flag: '🇱🇻', name: 'Latvia' },
  LBN: { flag: '🇱🇧', name: 'Lebanon' },
  LSO: { flag: '🇱🇸', name: 'Lesotho' },
  LBR: { flag: '🇱🇷', name: 'Liberia' },
  LBY: { flag: '🇱🇾', name: 'Libya' },
  LIE: { flag: '🇱🇮', name: 'Liechtenstein' },
  LTU: { flag: '🇱🇹', name: 'Lithuania' },
  LUX: { flag: '🇱🇺', name: 'Luxembourg' },
  MDG: { flag: '🇲🇬', name: 'Madagascar' },
  MWI: { flag: '🇲🇼', name: 'Malawi' },
  MYS: { flag: '🇲🇾', name: 'Malaysia' },
  MDV: { flag: '🇲🇻', name: 'Maldives' },
  MLI: { flag: '🇲🇱', name: 'Mali' },
  MLT: { flag: '🇲🇹', name: 'Malta' },
  MRT: { flag: '🇲🇷', name: 'Mauritania' },
  MUS: { flag: '🇲🇺', name: 'Mauritius' },
  MEX: { flag: '🇲🇽', name: 'Mexico' },
  MDA: { flag: '🇲🇩', name: 'Moldova' },
  MCO: { flag: '🇲🇨', name: 'Monaco' },
  MNG: { flag: '🇲🇳', name: 'Mongolia' },
  MNE: { flag: '🇲🇪', name: 'Montenegro' },
  MAR: { flag: '🇲🇦', name: 'Morocco' },
  MOZ: { flag: '🇲🇿', name: 'Mozambique' },
  MMR: { flag: '🇲🇲', name: 'Myanmar' },
  NAM: { flag: '🇳🇦', name: 'Namibia' },
  NPL: { flag: '🇳🇵', name: 'Nepal' },
  NLD: { flag: '🇳🇱', name: 'Netherlands' },
  NZL: { flag: '🇳🇿', name: 'New Zealand' },
  NIC: { flag: '🇳🇮', name: 'Nicaragua' },
  NER: { flag: '🇳🇪', name: 'Niger' },
  NGA: { flag: '🇳🇬', name: 'Nigeria' },
  MKD: { flag: '🇲🇰', name: 'North Macedonia' },
  NOR: { flag: '🇳🇴', name: 'Norway' },
  OMN: { flag: '🇴🇲', name: 'Oman' },
  PAK: { flag: '🇵🇰', name: 'Pakistan' },
  PAN: { flag: '🇵🇦', name: 'Panama' },
  PNG: { flag: '🇵🇬', name: 'Papua New Guinea' },
  PRY: { flag: '🇵🇾', name: 'Paraguay' },
  PER: { flag: '🇵🇪', name: 'Peru' },
  PHL: { flag: '🇵🇭', name: 'Philippines' },
  POL: { flag: '🇵🇱', name: 'Poland' },
  PRT: { flag: '🇵🇹', name: 'Portugal' },
  QAT: { flag: '🇶🇦', name: 'Qatar' },
  ROU: { flag: '🇷🇴', name: 'Romania' },
  RUS: { flag: '🇷🇺', name: 'Russia' },
  RWA: { flag: '🇷🇼', name: 'Rwanda' },
  SAU: { flag: '🇸🇦', name: 'Saudi Arabia' },
  SEN: { flag: '🇸🇳', name: 'Senegal' },
  SRB: { flag: '🇷🇸', name: 'Serbia' },
  SLE: { flag: '🇸🇱', name: 'Sierra Leone' },
  SGP: { flag: '🇸🇬', name: 'Singapore' },
  SVK: { flag: '🇸🇰', name: 'Slovakia' },
  SVN: { flag: '🇸🇮', name: 'Slovenia' },
  SOM: { flag: '🇸🇴', name: 'Somalia' },
  ZAF: { flag: '🇿🇦', name: 'South Africa' },
  SSD: { flag: '🇸🇸', name: 'South Sudan' },
  ESP: { flag: '🇪🇸', name: 'Spain' },
  LKA: { flag: '🇱🇰', name: 'Sri Lanka' },
  SDN: { flag: '🇸🇩', name: 'Sudan' },
  SWE: { flag: '🇸🇪', name: 'Sweden' },
  CHE: { flag: '🇨🇭', name: 'Switzerland' },
  SYR: { flag: '🇸🇾', name: 'Syria' },
  TWN: { flag: '🇹🇼', name: 'Taiwan' },
  TJK: { flag: '🇹🇯', name: 'Tajikistan' },
  TZA: { flag: '🇹🇿', name: 'Tanzania' },
  THA: { flag: '🇹🇭', name: 'Thailand' },
  TLS: { flag: '🇹🇱', name: 'Timor-Leste' },
  TGO: { flag: '🇹🇬', name: 'Togo' },
  TTO: { flag: '🇹🇹', name: 'Trinidad and Tobago' },
  TUN: { flag: '🇹🇳', name: 'Tunisia' },
  TUR: { flag: '🇹🇷', name: 'Turkey' },
  TKM: { flag: '🇹🇲', name: 'Turkmenistan' },
  UGA: { flag: '🇺🇬', name: 'Uganda' },
  UKR: { flag: '🇺🇦', name: 'Ukraine' },
  ARE: { flag: '🇦🇪', name: 'United Arab Emirates' },
  GBR: { flag: '🇬🇧', name: 'United Kingdom' },
  USA: { flag: '🇺🇸', name: 'United States' },
  URY: { flag: '🇺🇾', name: 'Uruguay' },
  UZB: { flag: '🇺🇿', name: 'Uzbekistan' },
  VEN: { flag: '🇻🇪', name: 'Venezuela' },
  VNM: { flag: '🇻🇳', name: 'Vietnam' },
  YEM: { flag: '🇾🇪', name: 'Yemen' },
  ZMB: { flag: '🇿🇲', name: 'Zambia' },
  ZWE: { flag: '🇿🇼', name: 'Zimbabwe' },
};

export function getCountry(code: string): { flag: string; name: string } {
  return COUNTRY_MAP[code?.toUpperCase()] ?? { flag: '🌍', name: code ?? 'Unknown' };
}

export function getFlag(code: string): string {
  return getCountry(code).flag;
}

export function getCountryName(code: string): string {
  return getCountry(code).name;
}
